# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Informe seu nome completo', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Informe seu endereço de E-mail', max_length=50, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
