# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='id',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
